name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jvm_flag: [
          "-Xms512m -Xmx1024m",
          "-XX:+UseG1GC",
          "-XX:+UnlockExperimentalVMOptions",
          "-XX:+UseZGC",
          "-XX:+UseStringDeduplication"
        ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and Test with Maven
        timeout-minutes: 15
        run: ./mvnw -B verify -DargLine="${{ matrix.jvm_flag }}"

      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          {
            echo 'COVERAGE<<EOF'
            coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
            echo "$coverage"
            echo 'EOF'
          } >> $GITHUB_ENV
        shell: bash


      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=24.46
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage is not improved."
            exit 1
          else
            echo "New coverage: $coverage%. Coverage is improved!"
          fi
        shell: bash
