name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jvm_flags: [
          "-Xms512m -Xmx1024m",
          "-XX:+UseZGC",
          "-Xmx256m -XX:+HeapDumpOnOutOfMemoryError",
          "-XX:MaxMetaspaceSize=128m -XX:MaxNewSize=256m -XX:SurvivorRatio=128 -XX:MaxTenuringThreshold=0",
          "-XX:+UseCompressedOops"
        ]
        common_jvm_flags_logs: ["-XX:+UnlockDiagnosticVMOptions -Xlog:gc*:file=jvm.log:time,level,tags -XX:+PrintFlagsFinal"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set environment variables
        run: |
          echo "MAVEN_OPTS=${{ matrix.jvm_flags }} ${{ matrix.common_jvm_flags_logs }}" >> $GITHUB_ENV
        shell: bash

      - name: Build and Test with Maven
        timeout-minutes: 15
        env:
          MAVEN_OPTS: "${{ matrix.jvm_flags }} ${{ matrix.common_jvm_flags_logs }}"
        run: |
          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage

      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
          echo "COVERAGE=$coverage" >> $GITHUB_ENV
        shell: bash

      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=24.46
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage is not improved."
            exit 1
          else
            echo "New coverage: $coverage%. Coverage is improved!"
          fi
        shell: bash

      - name: Display Build Log
        if: always()
        run: cat target/surefire-reports/*.txt || true
        shell: bash

      - name: Display JVM Log
        if: always()
        run: cat jvm.log
        shell: bash

      - name: Archive Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/*.jar
            target/surefire-reports/*.txt
            jvm.log
