name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        common_jvm_flags: ["-XX:+UnlockDiagnosticVMOptions -XX:+PrintGCDetails -XX:+PrintFlagsFinal -XX:+LogVMOutput -XX:LogFile=/path/to/jvm1.log"]
        jvm_flags: [
          "-Xms512m -Xmx1024m",
          "-XX:+UseG1GC",
          "-XX:+UnlockExperimentalVMOptions",
          "-XX:+UseZGC",
          "-XX:+UseStringDeduplication"
        ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set MAVEN_OPTS environment variable
        run: |
          echo "MAVEN_OPTS=${{ matrix.common_jvm_flags }} ${{ matrix.jvm_flags }}" >> $GITHUB_ENV
        shell: bash

      - name: Build and Test with Maven
        timeout-minutes: 15
        env:
          MAVEN_OPTS: "${{ matrix.common_jvm_flags }} ${{ matrix.jvm_flags }}"
        run: |
          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage

      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
          echo "COVERAGE=$coverage" >> $GITHUB_ENV
        shell: bash

      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=24.46
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage is not improved."
            exit 1
          else
            echo "New coverage: $coverage%. Coverage is improved!"
          fi
        shell: bash

      - name: Display JVM Log
        if: always()  # Ensure this step runs regardless of previous step outcome
        run: cat /path/to/jvm1.log
        shell: bash
