name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jvm_flags: [
          "-XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -XX:+PrintFlagsFinal",
          "-Xms512m -Xmx1024m -XX:+PrintGCDetails -XX:+PrintFlagsFinal -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+LogVMOutput -XX:LogFile=/path/to/jvm1.log",
          "-XX:+UseG1GC -XX:+PrintGCDetails",
          "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/path/to/heapdump",
          "-XX:+UseZGC",
          "-XX:+UseStringDeduplication"
        ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Log current JVM flag
        run: |
          echo "MAVEN_OPTS=${{ matrix.jvm_flags }}" >> $GITHUB_ENV
          echo "Running tests with JVM flag: ${{ matrix.jvm_flags }}"
        shell: bash

      - name: Build and Test with Maven
        timeout-minutes: 15
        env:
          MAVEN_OPTS: ${{ matrix.jvm_flags }}
        run: |
          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage

      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
          echo "COVERAGE=$coverage" >> $GITHUB_ENV
        shell: bash

      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=24.46
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage is not improved."
            exit 1
          else
            echo "New coverage: $coverage%. Coverage is improved!"
          fi
        shell: bash
